name: Android CI

on:
  workflow_dispatch:
    inputs:
      disabled:
        description: "Release workflow disabled"
        required: false
        default: "true"

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release workflow is disabled."
